xx

diff --git a/.github/actions/cache-check-verify/action.yaml b/.github/actions/cache-check-verify/action.yaml
--- a/.github/actions/cache-check-verify/action.yaml
+++ b/.github/actions/cache-check-verify/action.yaml
@@ -2,7 +2,6 @@ name: "composie action. check and verify cache."
 description: "Check cache"
 inputs:
   restorekey:
-    default: 'Windows-zzz-d41d8cd98f00b204e9800998ecf8427e'
     required: true
   architecture:
     default: 'all'
@@ -28,20 +27,23 @@ runs:
       continue-on-error: true
       shell: bash {0}
       run: |
-        cachedir=cache-${{ env.cachedir_ }}
-        test -d $cachedir && rm -rf $cachedir
-        test -d $cachedir || mkdir $cachedir
-        find downloads -type f -exec cp \{\} ./$cachedir \;
-        cd ./$cachedir
-        md5sum -c ../MD5SUMS
-        if [ $? -gt 0 ]; then
-          echo "cache=invalid" >> $GITHUB_OUTPUT
-          echo "cache=invalid"
-        else
-          echo "cache=valid" >> $GITHUB_OUTPUT
-          echo "cache=valid"
-        fi
-        echo "### VerifyCache :rocket:" >> $GITHUB_STEP_SUMMARY
+      echo ${{ inputs.architecture }}
+      foo=cache-${{ inputs.architecture }}
+      echo $foo
+      #  cachedir=cache-${{ env.cachedir_ }}
+      #  test -d $cachedir && rm -rf $cachedir
+      #  test -d $cachedir || mkdir $cachedir
+      #  find downloads -type f -exec cp \{\} ./$cachedir \;
+      #  cd ./$cachedir
+      #  md5sum -c ../MD5SUMS
+      #  if [ $? -gt 0 ]; then
+      #    echo "cache=invalid" >> $GITHUB_OUTPUT
+      #    echo "cache=invalid"
+      #  else
+      #    echo "cache=valid" >> $GITHUB_OUTPUT
+      #    echo "cache=valid"
+      #  fi
+      #  echo "### VerifyCache :rocket:" >> $GITHUB_STEP_SUMMARY
       env:
         cachedir_: cache-${{ inputs.architecture }}
 #--     - name: show result /${{ env.arc }}
